#!/bin/sh
[ -z "$VLAN_TT_TESTING" ] && VLAN_TT_TESTING=0
## This script is meant for use on Asus routers running in access point mode.
##  Any other use may remove your node from the networ ... or worse.
##
## for full details please see README.md

## Do things a bit differently if we are testing
##
## Set the environment vairable VLAN_TT_TESTING to 1 to enable testing mode
if [ "$VLAN_TT_TESTING" -eq 1 ]; then
	base="/tmp/mnt/ENTWARE/asus-ap-vlans-tt"
else
	base="/jffs/local"
fi

## get fucntions
. ${base}/bin/vlan_tt.func 

for int in $(ip link show | grep 'eth.\.' | awk '{print $2}' | awk -F@ '{print $1}'); do
	echo $int
done
